"""Reuse independent sample validation while original and generated bytes agree."""
from __future__ import annotations

from pathlib import Path

from argus_verticals.hardware.shared import evidence, native
from argus_verticals.hardware.spice import batch, raw
from argus_verticals.hardware.spice import validation as cached

from .evidence import PLAN, RESULTS
from .robustness import ASSESSMENT, validate_robustness


def _implementation_sources() -> dict[str, Path]:
    return {
        **{f"implementation/analog/{path.name}": path for path in Path(__file__).parent.glob("*.py")},
        "implementation/shared/evidence.py": Path(evidence.__file__),
        "implementation/shared/native.py": Path(native.__file__),
        **{f"implementation/spice/{path.name}": path for path in Path(raw.__file__).parent.glob("*.py")},
    }


_LOADED_IMPLEMENTATION = {key: path.read_bytes() for key, path in _implementation_sources().items()}


def validate_current(root: Path, *, state_root: Path | None = None) -> None:
    root = root.resolve()
    cached.validate_cached(
        root, "analog-validation", state_root=state_root,
        sources=lambda: cached.bound_sources(
            root, RESULTS, {PLAN, RESULTS, ASSESSMENT}, _implementation_sources(), _LOADED_IMPLEMENTATION,
        ),
        versions=lambda: {"ngspice_version": batch.version()},
        validate=lambda: validate_robustness(root),
    )
